### ISSUE TITLE
後払いで審査が落ちた「NG」場合、ステータスを審査NGとする。

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/canvath-web#100]

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 後払いで「決済失敗」となったせいなのか、ユーザー画面で注文履歴が見られなくなりました。
確認お願いします。
![budgets_admin_web](https://user-images.githubusercontent.com/23730555/33106204-55b8b5d2-cf74-11e7-8605-86d8150a7b8e.jpg)
![budgets](https://user-images.githubusercontent.com/23730555/33106229-7c89b68e-cf74-11e7-9058-ac93103566f5.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
