### ISSUE TITLE
クレカ決済時、決済完了していても自動で「決済済み」にならない

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/canvath-web#103]
動画はSlackにあげました。
試した注文番号は、#17112903230001です。

加えて、管理画面でキャンセルした時にPay.jpで返金(キャンセル)されませんでした。
こちらは、#17112903340001です。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 管理画面でキャンセルした時、Pay.jpでも返金処理させたいです。
