### ISSUE TITLE
グッズの価格表示はプリント代の込みで表示する

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/canvath-web#105]
グッズの価格表示がボディ代になっていることがある。

たまにプリント代が入ることもあるのですが、挙動が安定しません。
mediaship.com@gmail.com　/　541110

![budgets_](https://user-images.githubusercontent.com/23730555/33365651-41abd462-d52c-11e7-82f2-da78ccfcd840.jpg)
![budgets_](https://user-images.githubusercontent.com/23730555/33365655-4514c7f8-d52c-11e7-8783-286bf37e6634.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
