### ISSUE TITLE
ユーザ管理画面で納品書がダウンロードできません。

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#86]
納品書がダウンロードできなくなっています。
確認お願い致します
マスター管理画面でも納品書のダウンロードができませんでした。

![2017-11-09 20 18 11](https://user-images.githubusercontent.com/17405609/32603515-56f3c374-c58d-11e7-8fbf-ce8c954fffad.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov ダウンロードできました。
