### ISSUE TITLE
お届け先なのに新規ショップ登録になっている。

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#87]
![2017-11-09 20 23 03](https://user-images.githubusercontent.com/17405609/32603542-6dc9e470-c58d-11e7-855d-32195b315bbc.png)

お届け先登録　に変更してください。

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 変更しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov お届け先の方は治ったのですが、今度はショップ登録が「お届け先登録」になってます。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
