### ISSUE TITLE
マスター画面、画像ダウンロードでエラーがでる。

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#88]
マスター画面の画像ダウンロードで画像がダウンロードできません。
#17110214060001
上記注文番号
ものはiphone7です。

下記はエラーです。
![2017-11-09 20 28 31](https://user-images.githubusercontent.com/17405609/32603595-a0fbb9f4-c58d-11e7-84e9-d3d58bc80725.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。ご確認ください

**Comment by tomoyuki1110** [comment]
確認OK
