### ISSUE TITLE
マスター画面・生産アップ　で生産アップ中のままになっています。

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#89]
マスター画面・生産アップ　で生産アップ中のままになっています。

**Comment by tomoyuki1110** [comment]
![2017-11-09 20 39 02](https://user-images.githubusercontent.com/17405609/32603704-0df07ebe-c58e-11e7-8034-3f11845dcf7a.png)

生産アップエラー　となりました。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 請求の情報は設定してないためエラーとなりました。もっとわかりやすいエラーを設定しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov エラーはわかりやすくなりました。請求先設定したらアップできました。
![budgets_admin_web](https://user-images.githubusercontent.com/23730555/32890576-b1971166-cb12-11e7-89ca-b4e819f93737.jpg)
