### ISSUE TITLE
後払い購入が出来ない

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#90]
後払い購入がエラーでできなくなっています。
エラー内容添付します。
![2017-11-14 21 46 49](https://user-images.githubusercontent.com/17405609/32780922-5d936232-c986-11e7-9b1f-90cb1dd14c16.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@tomoyuki1110  後払い使えました。

**Comment by tomoyuki1110** [comment]
![2017-11-17 10 34 33](https://user-images.githubusercontent.com/17405609/32925068-465bd8ac-cb83-11e7-9f5b-fdc3f1a7f5e0.png)
私の方では画像のようなエラーがでます

**Comment by take-iwa** [comment]
@alexeypolitov @tomoyuki1110 後払いの申請にレンタル住所は使用できないため、ショップ情報のものを使うようにしてください。
'レンタル住所を使う'は、'納品書にレンタル住所を使う'にして、納品書でのみレンタル住所を使うようにお願いします。

更にすみません。
後払い申請にはユーザーの本名が必要です。
アカウントの発注者情報で性別ではなく名前の登録にしていただき、後払いの申請には名前にそちらを使うようにしていただけないでしょうか？

![budgets](https://user-images.githubusercontent.com/23730555/32927035-c63d8f5c-cb8d-11e7-9d9f-8d219da8e138.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 説明していただけますか？

**Comment by alexeypolitov** [comment]
@take-iwa スラックで話した通りで修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 後払いに使う請求用の住所ですが、csvで出力した時住所部分が入っていないとのことです。Budgets管理画面上では設定されているのですが。確認していただけますか？
![budgets_admin_web](https://user-images.githubusercontent.com/23730555/33105779-477de0fc-cf72-11e7-82b0-4d96105ceafb.jpg)
![https___maruiorimono_cybozu_com_g_message_file_image_view_csp_cid_361_rid_25_mid_714_rfid_877_hash_2e3dd4915faa9a082955830b7cbd55863fe63af6_nolog_1](https://user-images.githubusercontent.com/23730555/33105785-4e4531d8-cf72-11e7-9f55-90f93d5c6fe0.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 注文番号を教えてください

**Comment by take-iwa** [comment]
@alexeypolitov 201711200002 (17112008340001)です。
注文自体は、手動で住所入力して処理し「発送済み」になっています。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
