### ISSUE TITLE
各決済で支払い手数料を入れようとしたら、no_fee_expectedと出る

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#91]
各決済で支払い手数料を入れようとしたら、no_fee_expectedと出る
![2017-11-14 22 32 13](https://user-images.githubusercontent.com/17405609/32782448-c597ee8e-c98b-11e7-964d-b128b7f0f90a.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 値段は設定したいないたエラーとなってます。もっとわかりやすいエラーの文書を設定しました。ご確認ください

**Comment by take-iwa** [comment]
@tomoyuki1110 上限を入力して手数料設定できました。
