### ISSUE TITLE
オーナー管理画面で出荷済みにした後のヤマト・佐川の出荷番号はどこで見れますか？

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#93]
オーナー管理画面で出荷済みにした後のヤマト・佐川の出荷番号はどこで見れますか？

さらに、マスタ管理画面で、各ユーザが見れますか？

場所を教えてください。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 追加しました。ご確認ください

**Comment by tomoyuki1110** [comment]
配達会社はヤマトとありますが
配達番号はどこにかかれますか？

![2017-11-17 10 39 05](https://user-images.githubusercontent.com/17405609/32925108-8ae4b8b8-cb83-11e7-816d-25626dcfc0f6.png)

**Comment by alexeypolitov** [comment]
@take-iwa 説明していただけますか？

**Comment by take-iwa** [comment]
@tomoyuki1110 ヤマトで配送番号確認しました。

![_2017-11-22_10_15_28](https://user-images.githubusercontent.com/23730555/33104966-4581c60a-cf6e-11e7-8bb6-fa9377685687.jpg)
