### ISSUE TITLE
マスター管理画面、ユーザ管理画面で送付後のヤマト佐川＋配送番号情報が入るように

### ISSUE THREAD

**Issue by tomoyuki1110** [MaruiorimonoTeam/canvath-web#94]
マスター管理画面、ユーザ管理画面で送付後のヤマト佐川＋配送番号情報が入るように

上記現在ですと、確認できないので、確認できるようにお願いします

**Comment by alexeypolitov** [comment]
@tomoyuki1110 ユーザーの画面で配送番号など入ってます。マスター管理画面を確認してから連絡します

**Comment by tomoyuki1110** [comment]
すいません。場所がわからずで、教えてもらえればと思います。
マスターも同じです。あるなら教えてください。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 すみませんが大岩さんに相談していただけますか？すでに全ては説明済みですので

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 変更しました。ご確認ください
